<?php

/**
 * @file
 * Primary module hooks for HCPSS Notices module.
 */

/**
 * Implements hook_theme().
 */
function hcpss_notices_theme($existing, $type, $theme, $path) {
  return [
    'node__notice__full' => [
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function hcpss_notices_preprocess_node(&$variables) {
  if ($variables['node']->bundle() == 'notice') {
    $variables['notice_type'] = $variables['node']->get('field_notice_type')->value;
  }
}
